<?php

    $asean = array (
        '1' => array (
            'name'      => "Topic A",
            'title'     => "Maritime Security in Southeast Asia",
            'text'      => "Southeast Asia is a region with several conflicts and disputes, between the Asian countries, and between the Great Powers of the world. These conflicts and disputes take place, majority, in the waters that surround China and the Indochina region. The waters and territories of the South China Seas have been the subject of disputes for a long time, and actually, they appear to be escalating.
                            <br/>Therefore, the Maritime Security in the region is an important and polemic topic to be discussed in a regional forum, such as the ADMM+. The value of this discussion is related to the importance that the security of national and international waters have to the International System, since a great part of all international commerce and communications are done by maritime transportation, principally in the choke points of the Southeast Asia. Besides that, Oceans and Seas are used by all states to project power and national defense, being of great importance the control of the water.
                            <br/>Bearing these in mind, Southeast Asia is a substantial region to discuss Maritime Security, for all the territorial disputes that exist in the Asia-Pacific Ocean, and the conflicts that emerge between Great Powers in the region. In the South China Sea, China and ASEAN’s countries, such as Indonesia, Malaysia, Philippines and Vietnam, dispute the islands of Paracel and Spratly. In the case of the East China Sea, China and Japan dispute the control over the Senkaku/Diaoyu Islands. The unilaterally declared Air Defense Identification Zone (ADIZ) made by China in this Sea manages to increase the tensions in the region. Moreover, Japan also have territorial disputes over the Kuril Islands with Russia and over the Liancourt Rocks with South Korea.
                            <br/>Behind all these territorial disputes, there is an urgent need to discuss how the countries in the region will deal with the question of maritime sovereignty and the right to free and safety navigation in international waters. In the last year, China has developed an increasing program of islands building in the reefs of the Spratly Islands. However, the nature of these territories to International Law are not well defined, being object of dispute and increasing the tensions in the region.
                            <br/>In October 2015, an American vessel entered in this disputed area, showing that the United States are not willing to accept the more assertive Chinese presence in the region. This act are included in a broader American initiative, the \"Pivot to Asia\", an attempt to balance the increasing Chinese presence in the Asia-Pacific region. Other face of this strategy is the increasing maritime security cooperation between United States and countries like Japan, Philippines, Vietnam, Indonesia and Malaysia.
                            <br/>The delegates of the ADMM+ will have several challenges to address in UFRGSMUN, far beyond the territorial claims. The topic of Maritime security will involve the discussion of maritime and aerial sovereignty; the importance of the use of Sea Lines of Communication (SLOCs); the combat to nonstate threats, such as piracy; and negotiations to the implementation of the 2002 Declaration on the Conduct of Parties in the South China Sea (DOC).
                            <br/>The increasing tensions in the Asia-Pacific region are a threat to the International stability, and a deep discussion in Maritime Security matters between the countries in the region is needed to avoid further escalations. The final objective of this committee will be reach a broad and deep roll of actions to deal with Maritime Security in all its aspects, conciliating opposing interests that influence not only the regional balance of power, but the international system.",
            'refs'      => "Bradford, John. The growing prospects for maritime security cooperation in Southeast Asia. Naval War College Review, 2005: 62 - 86.
                            <br/>Lee, Victor Robert. South China Sea: China's Unprecedented Spratlys Building Program. April 25, 2015. http://thediplomat.com/2015/04/south-china-sea-chinas-unprecedented-spratlys-building-program/ (accessed January 19, 2016).
                            <br/>Panda, Ankit. For the ASEAN-China South China Sea Code of Conduct, Ninth Time Isn't the Charm. August 01, 2015. http://thediplomat.com/2015/08/for-the-asean-china-south-china-sea-code-of-conduct-ninth-time-isnt-the-charm/ (accessed January 19, 2016).
                            <br/>Parameswaran, Prashanth. US Announces Maritime Security Boost for Southeast Asia. November 19, 2015. http://thediplomat.com/2015/11/us-announces-boost-to-maritime-security-assistance-to-southeast-asia/ (accessed January 19, 2016).
                            <br/>Sciutto, Jim, and Katie Hunt. China says it warned and tracked U.S. warship in South China Sea. October 28, 2015. http://edition.cnn.com/2015/10/27/asia/us-china-south-china-sea/ (accessed January 19, 2016).
                            <br/>Slevison, Alice. An ADIZ with Chinese Characteristics. October 19, 2015. http://thediplomat.com/2015/10/an-adiz-with-chinese-characteristics/ (accessed January 19, 2016).
                            <br/>Tuan, Hoang Anh, and Nguyen Vu Tung. Growing Maritime Security Concerns in Southeast Asia. June 19, 2015. http://nationalinterest.org/feature/growing-maritime-security-concerns-southeast-asia-greater-13145 (accessed January 19, 2016)."

        ),
        '2' => array (
            'name'      => "Topic B",
            'title'     => "Counterterrorism in Southeast Asia",
            'text'      => "\"Terrorism\" is a widely debated term with no consensus on its definition. For instance, the Association of Southeast Asian Nations (ASEAN), due to differences in domestic issues and its members’ foreign policies, has never agreed on the meaning of \"terrorism\", even though the region has suffered several terrorists attacks in the lasts decades (Soesilowati 2011). Southeast Asia is one of the most affected regions by terrorism in the world, as it contains not only indigenous groups, but also organizations directly linked to al-Qaeda and to the self-proclaimed Islamic State (IS). The first one has been active in the region since the 1990s, getting recruits for their ranks and raising funds. Its major affiliate in the region is the regional group Jemaah Islamiyah (JI), which is the main suspect of carrying out the 2002 bombing in Bali - that took more than 200 lives - and several others attacks in the last decade (Banlaoi 2009). The second one is recently raising its presence also through alliances and propaganda. Several groups from Indonesia and Philippines have already pledged allegiance to IS. Moreover, some analysts estimates that are around 800-1000 supporters of IS in Southeast Asia , thus representing a great threat to the peace and stability in the region. In January 14 2016, the world witnessed the first terrorist attack carried out by IS in Southeast Asia which represented the definite establishment of a new force of instability in the region (Abuza 2016).
                            <br/>Besides traditional problems of the fight against terrorism, ASEAN members have several difficulties and differences on dealing with it. The complex domestic situation of some countries, such as Indonesia and Philippines, affects the national and the organization capacity to address properly to terrorism. Also, the heterogeneous foreign policies of the distinct countries in the region results on disagreements about the definition of terrorism and how to achieve one effective regional counterterrorism policy (Soesilowati 2011). Finally, although cooperating with the international community to suppress terrorists acts, ASEAN does not agree with foreign intervention in national issues. Some Southeast Asian nations - and Dialogue Partners, especially China and Russia - perceives the United States-led \"war on terror\" as a pretext to act in the region, jeopardizing their sovereignty.
                            <br/>Although having several differences dealing with terrorism, ASEAN members have never gave up seeking a regional policy to combat terrorism.  As a result, it has achieved some remarkable success. In the 2001 ASEAN Declaration on Joint Action to Counter Terrorism, the organisation did not reach a consensus on a clear definition of \"terrorism\", but the document stresses the profound threat that it represents to international peace and security and the urgency to take practical measures to counter it. The ASEAN Work Programme 2002 facilitates the exchange of information, greater legal cooperation, law enforcement cooperation, training programs and collaboration with ASEAN’s Dialogue Partners. Other example is the ASEAN convention on counter-terrorism, signed in 2007. It provides one regional framework to fight terrorism and specifically demarcates terrorist acts (Soesilowati 2011). Lastly, one recent success of cooperation on counterterrorism was the 2013 Counterterrorism Exercise (CTX) between forces of members of the ASEAN Defense Ministers Meeting Plus (ADMM+ 2015).
                            <br/>Therefore, it is of vital importance that ASEAN overpass its differences to counter, prevent and suppress the transnational danger represented by terrorism. Alongside its Dialogue Partners, ASEAN members should seek more intelligence sharing, operational capacity building and more joint exercises. ADMM+ must enhance the cooperation between the forces of its 18 members, but also must respect each country’s sovereignty, not allowing that the war on terror be an excuse to foreign intervention in the region.",
            'refs'      => "Abuza, Zachary. “Beyond Bombings: The Islamic State in Southeast Asia.” The Diplomat. 15 de January de 2016. http://thediplomat.com/2016/01/beyond-the-bombings-assessing-the-islamic-state-threat-in-southeast-asia/ (acesso em 24 de January de 2016).
                            <br/>ADMM+. “ADMM ASEAN.” About the ASEAN Defence Ministers’ Meeting (ADMM-Plus). 14 de January de 2015. https://admm.asean.org/index.php/about-admm/about-admm-plus.html (acesso em 23 de January de 2016).
                            <br/>ASEAN. “ASEAN Efforts to Counter Terrorism.” ASEAN. 04 de July de 2012. http://www.asean.org/?static_post=asean-efforts-to-counter-terrorism-this-paper-was-prepared-for-the-un-counter-terrorism-committee (acesso em 24 de January de 2016).
                            <br/>Banlaoi, Rommel C. Counter Terrorism Measures in Southeast Asia: How Effective are They? Manila: Yuchengco Center, 2009.
                            <br/>Bruce Vaughn, Emma Chanlett-Avery, Ben Dolven, Mark Manyin, Larry Niksch. Terrorism in Southeast Asia. Congressional Research, Washington, DC: Library of Congress, 2009.
                            <br/>Soesilowati, Sartika. “ASEAN’s Response to the Challenge of Terrorism.” Journal Unair 24, 2011: 228-241."
        )
    );

    $wb = array (
        '1' => array (
            'name'      => "Topic",
            'title'     => "Infrastructure Investments in Energy Transition in Caucasus and Central Asia (CCA)",
            'text'      => "Southeast Asia is a region with several conflicts and disputes, between the Asian countries, and between the Great Powers of the world. These conflicts and disputes take place, majority, in the waters that surround China and the Indochina region. The waters and territories of the South China Seas have been the subject of disputes for a long time, and actually, they appear to be escalating.
                            <br/>Therefore, the Maritime Security in the region is an important and polemic topic to be discussed in a regional forum, such as the ADMM+. The value of this discussion is related to the importance that the security of national and international waters have to the International System, since a great part of all international commerce and communications are done by maritime transportation, principally in the choke points of the Southeast Asia. Besides that, Oceans and Seas are used by all states to project power and national defense, being of great importance the control of the water.
                            <br/>Bearing these in mind, Southeast Asia is a substantial region to discuss Maritime Security, for all the territorial disputes that exist in the Asia-Pacific Ocean, and the conflicts that emerge between Great Powers in the region. In the South China Sea, China and ASEAN’s countries, such as Indonesia, Malaysia, Philippines and Vietnam, dispute the islands of Paracel and Spratly. In the case of the East China Sea, China and Japan dispute the control over the Senkaku/Diaoyu Islands. The unilaterally declared Air Defense Identification Zone (ADIZ) made by China in this Sea manages to increase the tensions in the region. Moreover, Japan also have territorial disputes over the Kuril Islands with Russia and over the Liancourt Rocks with South Korea.
                            <br/>Behind all these territorial disputes, there is an urgent need to discuss how the countries in the region will deal with the question of maritime sovereignty and the right to free and safety navigation in international waters. In the last year, China has developed an increasing program of islands building in the reefs of the Spratly Islands. However, the nature of these territories to International Law are not well defined, being object of dispute and increasing the tensions in the region.
                            <br/>In October 2015, an American vessel entered in this disputed area, showing that the United States are not willing to accept the more assertive Chinese presence in the region. This act are included in a broader American initiative, the \"Pivot to Asia\", an attempt to balance the increasing Chinese presence in the Asia-Pacific region. Other face of this strategy is the increasing maritime security cooperation between United States and countries like Japan, Philippines, Vietnam, Indonesia and Malaysia.
                            <br/>The delegates of the ADMM+ will have several challenges to address in UFRGSMUN, far beyond the territorial claims. The topic of Maritime security will involve the discussion of maritime and aerial sovereignty; the importance of the use of Sea Lines of Communication (SLOCs); the combat to nonstate threats, such as piracy; and negotiations to the implementation of the 2002 Declaration on the Conduct of Parties in the South China Sea (DOC).
                            <br/>The increasing tensions in the Asia-Pacific region are a threat to the International stability, and a deep discussion in Maritime Security matters between the countries in the region is needed to avoid further escalations. The final objective of this committee will be reach a broad and deep roll of actions to deal with Maritime Security in all its aspects, conciliating opposing interests that influence not only the regional balance of power, but the international system.",
            'refs'      => "IMF. 2012. Middle East and Central Asia Department. The Caucasus and Central Asia: Transitioning to Emerging Markets.  https://www.imf.org/external/pubs/ft/dp/2014/1402mcd.pdf.
                            <br/>IMF. 2015. World Economic and Financial Surveys. Regional Economic Outlook: Middle East and Central Asia. https://www.imf.org/external/pubs/ft/reo/2015/mcd/eng/pdf/mreo1015.pdf.
                            <br/>Kähkönen, Juha. 2013. The Caucasus and Central Asia: From Transition to Emerging Markets. The Atlantic Council. July 19. http://pt.slideshare.net/atlanticcouncil/130619-kahkonen-ccapresentation.
                            <br/>Papandreou, Andreas, and Ruzzenenti, Franco. 2015. On the effects of fóssil fuel prices on the transition towards a low carbon energy system. http://fessud.eu/wp-content/uploads/2015/03/Papandreou_Ruzzeneti_Effects-of-fossil-fuel-prices-on-transition-to-low-carbon-energy-part-A-working-paper-89.v2.pdf."

        ),
    );

    $disec = array (
        '1' => array (
            'name'      => "Topic",
            'title'     => "Militarization of International Straits and Maritime Choke Points",
            'text'      => "International straits are understood as natural maritime passages separating two land masses and uniting two portions of sea. To be considered an international strait it must encompass the territorial sea of one or more States and be used for international navigation (Martín 2010). Choke points are here analyzed in the military and economic context. Therefore, maritime choke points are international straits that (i) cannot easily be bypassed, (ii) have huge economic importance for the international trade of oil and gas and (iii) offer the opportunity to prevent the movement of an opponent military force (Emerson & Stevens 2012). Historically, maritime navigation has been one of the most important transportation means of human history, showing that the access to international waters represents a main issue of global politics. Straits, strategic passages and maritime choke points have taken important parts in ancient and modern events, being a fundamental part of strategic and operational conducts of most nations in all continents. From the Age of Discovery, in the Americas, to the World Wars, in Europe, the Chinese Civil War, in Asia, and the Iran-Iraq War and the Invasion of Iraq, in 2003, straits were involved as important parts of each conjunctural development (Creighton 1988, Martín 2006, Paulmann, 2013)
                            <br/>Nowadays, two thirds of total petroleum transportation is performed by maritime shipping. In that sense, it is clear that the whole global energy system - and the economy of many countries - is extremely vulnerable to maritime choke points. Besides, the entire military mobilization capacity of some countries is heavily dependent on maritime transportation, so their power projection find a great barrier in the closure of sea lines of communication. There are some key straits that can be considered choke points and, therefore, represent a higher risk for international economy, security and politics: the Straits of Hormuz, Malacca, Bab-el-Mandeb and Bosphorus. These focal points gather the interest of main international powers, since their importance is a reflex of growing maritime circulation, proximity to politically unstable nations, terrorism and piracy. Therefore, the militarization of such points can represent, above all, a political instrument for dissuasion, or an “Achilles’ heel” of the global economy and security (Rodrigue 2004, Emerson & Stevens 2012, Martin 2010, Huber 2003, Roach 2005, Massey 2008, Gresh 2010, Lineback 2001, Chossudovsky 2010). ",
            'refs'      => "Chossudovsky, Michel. 2015. Global Research. Global Research. April 4. http://www.globalresearch.ca/yemen-and-the-militarization-of-strategic-waterways/17460.
                            <br/>Creighton, Neal. 1988. Panama Canal Fades for Military. Chicago Tribune. April 13. http://articles.chicagotribune.com/1988-04-13/news/8803080422_1_panama-canal-canal-zone-air-base.
                            <br/>Emmerson, Charles, and Paul Stevens. 2012. Maritime Choke Points and the Global Energy System: Charting a Way Forward. Energy, Environment and Resource Governance, January: 1-12.
                            <br/>Gresh, Geoffrey F. 2010.  Traversing the Persian Gauntlet: US Naval Projection and the Strait of Hormuz. The Fletcher Forum of World Affairs: 41-56.
                            <br/>Huber, Mark M. 2003. Chokepoint Control: Operational Challenges for Blue-Water Navies. Newport: Naval War College.
                            <br/>Lineback, Neal G. 2001. Geography in the News. Geography in the News. March 30. http://media.maps101.com/SUB/GITN/ARCHIVES/PDF/565_033001oilc.pdf
                            <br/>Martín, Ana G. Lopez. 2010. International Straits: Concept, Classification and Rules of Passage. Heidelberg: Springer.
                            <br/>Martín, Félix. 2006. Militarist Peace in South America. New York: Palgrave McMillan.
                            <br/>Massey, Anthony S. 2008. Maritime Security Cooperation in the Strait of Malacca. Thesis, Monterey: Naval Postgraduate School.
                            <br/>Paulmann, Johannes. 2012. The Straits of Europe: History at the Margins of a Continent. 26th Annual Lecture of the GHI, Washington DC: GHI.
                            <br/>Roach, Ashley. 2005. “Enhancing Maritime Security in the Straits of Malacca and Singapore.” Journal of International Affairs: 97-116.
                            <br/>Rodrigue, Jean-Paul. 2004. “Straits, Passages and Chokepoints: A Maritime Geostrategy of Petroleum Distribution.” Cahiers de Géographie du Québec, December: 357-374."

        ),
    );

    $icj = array (
        '1' => array (
            'name'      => "Topic A",
            'title'     => "Obligations concerning Negotiations relating to Cessation of the Nuclear Arms Race and to Nuclear Disarmament (Marshall Islands v. Pakistan)",
            'text'      => "Since the beginning of the Cold War, the matter of nuclear weapons had increasingly became a most influential factor to the relations between States. Throughout the twentieth-century, these weapons were enhanced in range and power, elevating their already alarming potential for devastation. It was in order to limit the spread of nuclear weapons that the international community adopted the Treaty on the Non-Proliferation of Nuclear Weapons (NPT) in 1968, which calls for the secession of the nuclear arms race and abandonment of nuclear weapons.
                            <br/>The Non-Proliferation Treaty was adopted in 1 July 1968, and entered into force on 20 March 1970. The NPT recognizes five States as nuclear-weapon states: the United States, Russia, the United Kingdom, France, and China. A total of 190 parties have joined the Treaty, including the five nuclear-weapon States. More countries have ratified the NPT than any other arms limitation and disarmament agreement, a testament to the Treaty's significance.
                            <br/>In addition to the five NPT nuclear-weapons States, four non-NPT States are known to possess nuclear weapons: India, Pakistan, Israel and North Korea. Pakistan has released no official doctrine regarding possible use of nuclear weapons. Actually, the country has refused to adopt a no-first-use policy. Also, Pakistan has not signed or ratified the 1966 Comprehensive Nuclear-Test-Ban Treaty, nor has it in recent years given any indication that it intends to do so. It is estimated that over the next ten years Pakistan’s nuclear weapons stockpile could potentially reach 150-200 warheads – a number comparable to the future British nuclear stockpile.
                            <br/>In this sense, the Republic of the Marshall Islands, a non-nuclear-weapon State Party to the NPT, which have been scene of the dire consequences of nuclear weapons, submitted in 24 April 2014, before the ICJ, application against the Islamic Republic of Pakistan. The applicant claims that Pakistan has breached its obligations under customary international law, including specifically its obligation to pursue in good faith negotiations to cease the nuclear arms race at an early date, as well as to pursue in good faith negotiations leading to nuclear disarmament in all it aspects under strict and effective international control. Also, Pakistan has breached its obligations to perform its international legal obligations in good faith.
                            <br/>Therefore, the ICJ judges must decide whether or not if Pakistan has fulfilled, all its legal obligations in relation to cessation of the nuclear arms race and to nuclear disarmament, in a timely manner and in accordance to good faith.",
            'refs'      => "International Court of Justice (ICJ). 2016. Obligations concerning Negotiations relating to Cessation of the Nuclear Arms Race and to Nuclear Disarmament (Marshall Islands v. Pakistan). Application instituting proceedings (field in the Registry on 24 April 2014). Accessed 23 January. http://www.icj-cij.org/docket/files/159/18294.pdf.
                            <br/>Nikitin, Boris S. 2010. International Law and Nuclear Weapons: Does the Continued Development of Advanced Nuclear Weapons Violate International Law? Student Pulse, 2(01), p.1. http://www.studentpulse.com/a?id=140.
                            <br/>United Nations Office for Disarmament Affairs (UNODA). 2016. Treaty on the Non-Proliferation of Nuclear Weapons (NPT). Accessed 2 February. http://www.un.org/disarmament/WMD/Nuclear/NPT.shtml. "

        ),
        '2' => array (
            'name'      => "Topic B",
            'title'     => "Alleged Violations of Sovereign Rights and Maritime Spaces in the Caribbean Sea (Nicaragua v. Colombia)",
            'text'      => "Located in the south of the Caribbean Sea, Nicaragua and Colombia are undergoing territorial disputes over the Archipelago of San Andrés, Providencia and Santa Catalina, the surrounding waters, fishing rights and the rights to natural resources within the disputed maritime spaces. The case already has been taken to the ICJ in 2007 and 2012. In 2007, the court recognized the full sovereignty of Colombia over the islands of San Andrés, Providencia and Santa Catalina, but left the sovereignty of some islands still undecided. In 2012, the ICJ reached the same verdict.  In November, 2013, Nicaragua once again filed the case to the ICJ regarding the previous judgment in 2012, so the dispute has remained unresolved.
                            <br/>In this sense, the present dispute concerns the alleged violations of Nicaragua’s sovereign rights and maritime zones declared by the Court’s Judgment of 19 November 2012, in the ICJ previous case Territorial and Maritime Dispute (Nicaragua v. Colombia), and the supposed threat of the use of force by Colombia in order to implement these alleged violations (ICJ 2015).
                            <br/>Colombia, on the other hand, affirms that the International Court of Justice cannot adjudicate on the matters brought by Nicaragua's Application of 26 November 2013. The Application lodged by Nicaragua on 26 November 2013 concerns compliance with the Judgment of 19 November 2012. According to the respondent, this is clear from the submissions set forth in the Application, which Nicaragua has sought, without success, to reformulate and distance itself from the Memorial. The Republic of Colombia also says that the alternative basis for jurisdiction claimed by Nicaragua, an alleged inherent power in the Court to ensure compliance with its own judgments, confirms that Nicaragua's focus in instituting the present proceedings was on compliance with the Judgment (ICJ 2014).
                            <br/>This dispute between Nicaragua and Colombia is not merely a territorial dispute regards to a prospective area regarding fishing, oil, and gas. Such a long conflict has definitely influenced the diplomatic relations between the two countries. The court is therefore invited to discuss about the main thesis and issues that guide this case, in order to not only ponder over each side’s arguments but also the reason why this case remains unresolved despite the previous trials.",
            'refs'      => "International Court of Justice (ICJ). 2016. Alleged Violations of Sovereign Rights and Maritime Spaces in the Caribbean Sea (Nicaragua v. Colombia). Application instituting proceedings (field in the Registry on 26 November 2013). Accessed 2 February. http://www.icj-cij.org/docket/files/155/17978.pdf.
                            <br/>______. 2016. Alleged Violations of Sovereign Rights and Maritime Spaces in the Caribbean Sea (Nicaragua v. Colombia). Preliminary Objections of The republic of Colombia – Volume I (field in the Registry on 19 December 2014). Accessed 2 February. http://www.icj-cij.org/docket/files/155/18788.pdf.
                            <br/>______. 2016. Alleged Violations of Sovereign Rights and Maritime Spaces in the Caribbean Sea (Nicaragua v. Colombia). Preliminary Objections of The republic of Colombia – Volume II (field in the Registry on 19 December 2014). Accessed 2 February. http://www.icj-cij.org/docket/files/155/18790.pdf.
                            <br/>______. 2016. Alleged Violations of Sovereign Rights and Maritime Spaces in the Caribbean Sea (Nicaragua v. Colombia). Written Statement of the Republic of Nicaragua to the Preliminary Objections of the Republic of Colombia (field in the Registry on 20 April 2015). Accessed 2 February. http://www.icj-cij.org/docket/files/155/18792.pdf."
        )
    );

    $oea = array (
        '1' => array (
            'name'      => "Topic A",
            'title'     => "Transnational Organized Crime",
            'text'      => "There is no doubt that Transnational Organized Crime represents a great threat for the whole world, considering the special weight it has on the Americas. Causing serious social, political and economical consequences, Organized Crime limits many nations’ agendas as far as its combat canalizes a significant part of efforts and resources, reducing its capacity on meeting fundamental points for each country’s development.
                            <br/>It not only persists but also evolves, passing through a mutation process along the hemisphere: criminal organisms are getting more and more decentralized - dedicating itself to different negotiations, legal or illegally - and transnationally, with cells and activities in many countries, possessing their own expansion rotes and frequently scaping from government’s control (Pagliari 2009, Szklarz 2014).
                            <br/>On dealing with the problem nationally while facing the rise in pressure in only one country, those nets search for new routes and opportunities; it gets clear, therefore, that the problem must be approached under a coordinative perspective among the Americas. The Organization of American States General Assembly, the only regional forum that puts together all the countries from this continent, have been canalizing efforts on handling the subject for a great while, as the Hemispherical Plan Against Transnational Organized Crime stands out (Oea 2015).
                            <br/>Despite its length, this Plan will complete ten years soon and the problem still remains severe. A reevaluation of the adopted strategies is necessary to answer the transnational organized crime’s persistence and mutation in a more effective way in every country in the continent. Besides the plan itself, it is appropriate to discuss new combat forms against this threat, having in mind cooperation perspectives of solving the issue (Pagliari 2009). The subjectivity of the operational concepts also deserves special attention, both on what is considered organized crime and on the approaches offered by the States on beating it.  Aiming to stimulate the debate on this fundamental subject on the America’s agenda, which is strongly connected to many other problems that threaten the region, UFRGSMUN brings this topic to its XIV edition. ",
            'refs'      => "OEA. 2015. “Relatório da Secretaria de Segurança Multidimensional sobre a Implementação do Plano Hemisférico de Ação contra a Criminalidade Organizada Transnacional .”
                            <br/>Pagliari, Graciela de Conti. 2009. “Segurança na América do Sul: problemas e atores.” In: O Brasil e a Segurança na América do Sul, por Graciela de Conti Pagliari, 87-124. Curitiba: Juruá.
                            <br/>Szklarz, Eduardo. 2014. “A dinâmica do crime organizado na América Latina.” Infosur Hoy. April 7. http://www.scivortex.org/vortex/news/Entries/2014/4/7_The_dynamics_of_organized_crime_in_Latin_America._Eduardo_Salcedo-Albaran_at_Info_Sur_Hoy_3.html."
        ),
        '2' => array (
            'name'      => "Topic B",
            'title'     => "The Situation in Venezuela ",
            'text'      => "The situation in Venezuela is crucial regarding security and stability in South America. Its importance for the Americas’ statement as a world reference on democracy brought the issue to XIV UFRGSMUN, which proposes the current situation in Venezuela as a matter of discussion on the Organization of the American States General Assembly. Since its independence, Venezuela has been struggling against political instability caused by brief authoritarian and democratic governments (Neves, 2010). And it has not been different on the last decades.
                            <br/>After relative stability during Hugo Chavez’s government, political tensions returned with great strength in 2013. Chavez's death, Maduro’s sworn in as president and the significant falling on oil prices empowered oppositional movements, which stimulated political divisions. In 2014, many violent protests followed by strong repression reactions by the government put a Civil War threat close to the Venezuelan situation, what could be seen on the country’s economy. Registering troublesome problems caused by the lack of products and economic rates even more fragilized (O Globo 2014), the December 2015 parliamentary elections opened space for a meaningful victory for the opposition party, which occupied most of the vacancies on their unicameral parliament, known as Venezuela’s National Assembly (Lafuente 2015).
                            <br/>Although Nicolás Maduro had recognized the opposition’s victory in a first moment, his government decided to call for the Supreme Court of Justice to contest 8 candidates’ mandates (O Observador 2016), bringing back instability and political conflict to Venezuelan situation (Sputnik News 2016). The fragile Venezuelan democracy has been facing several violations on Human Rights, a clear democratic institutions’ undermining and controversial economical policy adopted by the government. Those are some of the key points on the discussion proposed by UFRGSMUN on this committee meeting. We count on our delegates to get closer to an agreement among all State members, dealing diplomatically with the current situation of Venezuela.",
            'refs'      => "Lafuente, Javier. 2015. “Venezuela dá as costas ao chavismo.” El País. December 8. http://brasil.elpais.com/brasil/2015/12/07/internacional/1449454340_373673.html.
                            <br/>Neves, Rômulo Figueira. 2010. Cultura Política e Elementos de Análise da Política Venezuelana. Brasília: Fundação Alexandre de Gusmão (FUNAG).
                            <br/>O Globo. 2014. “Venezuela: o país das quatro taxas de câmbio.” O Globo. February 26. http://oglobo.globo.com/mundo/venezuela-pais-das-quatro-taxas-de-cambio-11715476.
                            <br/>O Observador. 2016. “Venezuela: três deputados da oposição suspensos pedem para abandonar parlamento.” O Observador. January 13. http://observador.pt/2016/01/13/venezuela-tres-deputados-da-oposicao-suspensos-pedem-abandonar-parlamento/
                            <br/>Sputnik News. 2016. “Assembleia Nacional venezuelana vive clima de guerra.” Sputnik News. January 12. http://br.sputniknews.com/mundo/20160112/3277429/assembleia-nacional-venezuelana-guerra.html. "
        )
    );

    $au = array (
        '1' => array (
            'name'      => "Topic A",
            'title'     => "Gender issue in conflict: violence against women as a weapon of war",
            'text'      => "In 2009, the African Union Commission declared the decade 2010-2020 as the African Women's Decade. The Decade's goal is to accelerate the implementation of commitments on gender equality and the empowerment of women at all levels of the continent, especially in cases of wars and conflicts. In Africa, incidents of violence against women in armed conflicts were always present. Thousands of women were subjected to a series of violations, including forced prostitution, rape, mutilation and economic exploitation. Because of this, the Council of Peace and Security of the African Union created the program \"Women, gender, peace and security\", which has guidelines for preventing and combating violence against women in war.
                            <br/>In Africa, cases of sexual violence and marginalization of women are still strong structural elements of conflict situations, the main means of subjugation of nations and ethnic groups. Internationally, with the UNSC Resolution 1325 (2000) on Women, Peace and Security Resolution 1820, sexual violence is explicitly linked as a tactic of war. However, within Africa there are few peace agreements that point to sexual violence as a war crime, hindering its mapping and implementation of effective mechanisms for combating it.
                            <br/>Despite the progress already made by the African Union with regard to human rights, especially with regard to the creation of mechanisms to prevent and point out the violation of rights of women and children in conflicts, the African Union needs to ensure that these mechanisms are indeed ratified and implemented by member countries. The protocol on the rights of women in Africa, also known as the Maputo Protocol, has not been signed by some countries, and 21 signatories also present difficulties in ratifying it.
                            <br/>The absence of mechanisms to penalize countries that do not ratify it increases the difficulties in implementing the same. Another important issue is the inclusion of women in conflict resolution processes, which is still low, since women represent a minimum percentage of negotiators and mediators of conflicts
                            <br/>Therefore, it is necessary that the Peace and Security Council of the African Union discuss female representation with regard to peace-building processes, placing woman in a position to decide and participate in the security agenda. It is important that the Security Council works on ways to qualify sexual violence as a weapon of war, not only pointing the importance of protecting women in conflict situations in the same way that emphasizes the protection of children, but by putting them it in the center decision of securitarian issues.",
            'refs'      => ""
        ),
        '2' => array (
            'name'      => "Topic B",
            'title'     => "The Situation in Burundi ",
            'text'      => "Among the smallest countries in extension in African Continent, Burundi is found in the region of the Great Lakes, bordering Rwanda, Tanzania and the Democratic Republic of Congo. According to the World Bank, the country is ranked as one of the poorest countries in the world, with almost 70% of its population living below the poverty line. In addition to poverty, Burundi is marked by ethnic tensions that haunt the country since before its independence.
                            <br/>Since the colonial period, in which the country was unified with Rwanda, through its independence and emancipation in 1962 to the present, Burundi had a history marked by violence. Such marks are given mainly by inter-ethnic conflict between Tutsis, who were a minority and dominated the state's politics, and Hutus, who made up 85% of the population. These interethnic tensions were strongly encouraged and exacerbated by Belgium, Metropolis time of Ruanda-Urundi, which gave support to the Hutus. Driven by socio-economic policy issues, these tensions led to a civil war between 1993 and 2006, which made thousands of refugees and killed about 200,000 people. Only in 2006 the government and the National Liberation Forces signed a cease-fire, ending the bloodbath.
                            <br/>The crisis now facing the country today scares mainly by the fear that history will repeat itself. Begun in 2015, it had the immediate cause of the third candidacy of President Pierre Nkurunziza, after two consecutive terms, which characterized an unconstitutional act, in accordance with the Constitution of the Republic of Burundi. Pierre Nkurunziza appeared on the political scene to break the centuries-old sequence of Tutsi rulers and became president in his first term, from parliamentary vote - which is why his supporters claim the legitimacy of the third term. Subsequent to the announcement of his candidacy, started riots in the country that intensified when the Supreme Court approved the competition's president. Proportional to the increase of the popular demonstrations was the government repression that classified them as terrorists.
                            <br/>Even with the request of the African Union for the elections to be postponed and thus the country could achieve greater stability, Pierre Nkurunziza was reelected, which further aggravated the situation in the country. From that moment the political and social instability was restored completely and brought up the fear that the conflict in the Republic of Burundi becomes ethnic, worry that it gained strength due to allegations that the most affected by the government's attacks, ethnic Hutu, were of Tutsi origin .The African Union has already offered to help the country during the current crisis, sending 5,000 troops to peacekeeping to ensure the safety of burundinense population, however this aid has been denied by the officials of the country.
                            <br/>Given this scenario, it is extremely important that the Council of Peace and Security of the African Union (CPSUA) be able to find viable and specific solutions to the crisis in the Republic of Burundi. According to the UN, at least 439 people have been killed in Burundi since the beginning of the conflict, in addition to the 230,000 people who have become internally displaced or refugees in the Great Lakes region. This conflict affects the region as a whole, so it is up to the members of the Council of Peace and Security of the African Union try to stop the political instability before the conflict affects more people in the country, without the intervention of outside interests in the region. African problems, African solutions.",
            'refs'      => ""
        )
    );

    $unea = array (
        '1' => array (
            'name'      => "Topic A",
            'title'     => "Exploration of natural resources and sustainable development: the environmental dimension of corporate social responsibility",
            'text'      => "The role that enterprises can play on the promotion of sustainable development in a global scale cannot be neglected. Besides adopting measurements to mitigate the negative impacts of their activities on the environment, those enterprises can promote policies that effectively contribute to the achieving of the Sustainable Development Goals (SDGs) announced on the 2030 Agenda. These measures, that transcend the compulsory initiatives fixed on national and international regulatory frameworks, are named Corporate Social Responsibility (CSR).
                        	<br/>When it comes specifically to extractive industries, it is undeniable that, for a long time, they have underestimated environmental issues on their development process, and, in a certain way, isolated them of their agenda. Nevertheless, over the past decades, this topic has become central on the discussions over sustainable growth, which was the main issue in forums like ECO-92, Rio+10 and Rio+20. Besides all the binding documents that resulted from these meetings and the rising depletion of global natural resources, actions from extractive industries that result on degradation of the environment continue happening.
                        	<br/>Bearing in consideration the economic relevance of the extractive sector – especially for developing countries – and the need to reinforce these industries’ commitment with the environment, emerges the discussion over the environmental dimension of corporate social responsibility. Above all, also rises the discussion on how can the public sector contribute to the dissemination and consolidation of the CSR on the sectors that rely on the exploitation of natural resources, which have direct impact over the environment, through intergovernmental initiatives?",
            'refs'      => ""
        ),
        '2' => array (
            'name'      => "Topic B",
            'title'     => "The role of natural resources in prevention of conflicts and in peacebuilding and peacekeeping ",
            'text'      => "The role of natural resources and the environment as – paradoxically – inducers of conflagrations and as promoter of construction and maintenance of peace has been noticed, in the past two decades, as substantial in terms of global security. These resources – both renewable and non-renewable – influence the path of the conflicts derived from them and may serve as catalyzers, in addition, to the formulation of answers to the risks of these events, as well as a of roads to peacebuilding and peacekeeping.
                            <br/>Natural resources carry with them the conditions that feed a conflagration – in inter or intrastate levels – in its period of start, as well as in its perpetuation: many are the cases in which this occurred – and still occurs – as in Afghanistan, Côte D’Ivoire, Central African Republic, Democratic Republic of Congo and Uganda. Factors as climate change, population growth and environmental degradation, when gathered to the growing demand for natural resources, act as fuels to intensifying competition among communities, groups and/or countries for the access, ownership or use of natural resources. In cases where the conflict has been triggered, it is understood that there is a need to reverse the allocation of these resources as inciters of disputes to promoter of peace, both in peacebuilding and peacekeeping. However, there is a low coefficient of aggregation of knowledge about resource management and the way they can corroborate allied practices of sustainable development.
                            <br/>There is a need to impregnate caution strategies in the management of natural resources in order to prevent them from inciting conflict, as well as united policies which address the integration of the environment in post-conflict planning. Issues as the strengthening the role of women in peace processes, the improvement of techniques of environmental management, inspection and supervision of mining activities (as well as trade) and environmental transgressions should be put in the agenda of multilateral fora. Given this and the adoption of the Agenda 2030 for Sustainable Development, which includes the newly established Sustainable Development Goals and, in particular, the Goal 16, which posits the promotion of peaceful and inclusive societies to the sustainable development, there is a pressing need to bring the discussion on the role of natural resources in conflict prevention and in peacebuilding and peacekeeping to the agenda of the main decision-making body of the United Nations on environmental issues, the United Nations Environmental Assembly (UNEA).",
            'refs'      => ""
        )
    );

    $unsc = array (
        '1' => array (
            'name'      => "Topic A",
            'title'     => "Peace Operations and Statebuilding in Post-Conflict Situations",
            'text'      => "In post-conflict situations, despite the supposed absence of war, there is not necessarily real peace. The international community is aware of the devastating effects of war and the necessity of supporting communities and countries trying to restore peace and rebuild what has been destroyed. Besides human loss and physical destruction, conflict also leads to the collapse of the institutions that make a stable society function. The end of fighting gives way to work towards lasting peace, but that requires the establishment of viable institutions, capable of ensuring lasting security for the entire population (Brahimi 2007).
                            <br/>The UN peacekeeping operations, under the mandate of the Security Council, have played a major role in international peace and security since the end of the Cold War. Notwithstanding, about half of the countries where peace operations were said to have successful endings actually fell back into conflict within five years or less – Afghanistan and Haiti are prominent examples (Brahimi 2007). Peacekeeping missions have often been deployed to areas with little or no peace to keep, and therefore they have progressively assumed an increasing set of peace enforcement and peacebuilding tasks. Recent peacekeeping missions demonstrate the willing of the Council in authorizing the use of military force and promoting deeper-rooted interventions aimed at restoring state authority (Labuda 2015).
                            <br/>Thereby, the UN acquired a growing relevance in exercising state-like functions where domestic governance lacks. Rebuilding institutional framework shattered during conflict has become as important, if not more important than physical infrastructure, and involves a wide range of activities: electoral processes, reintegration and national reconciliation of former combatants and the establishment of the rule of law (Kumar 1997). Without functioning and self-sustaining government systems, peace and development will be, at best, short-lived. In this regard, amplifying the conception of peacekeeping missions, including elements of peacebuilding and statebuilding, has been of utmost importance. Yet, it is necessary to delimitate such authoritative functions, what invokes the so-called “light footprint” approach, according to which large international missions must not duplicate local skills in a way that undermines national institutional development and the legitimate aspirations of the local people (Brahimi 2007).
        	                <br/>In the discussion, delegates are called upon to reflect the importance the UN has in reaching long-lasting peace and security in conflict-affected regions. More than simply evaluating the role and effectiveness of peace operations, the reform of peacekeeping must be addressed, towards expanding its scope and providing it with clear and realist mandates. The attempts to promote democratic institutions in collapsing states, though, have allegedly and historically been considered a Western-led experience with inherent imperialist interests, and have long orientated UN policies (von Bogdandy, et al. 2005). This raises political instability and polarization between international actors, and makes room for a broader debate on whether UN interventions might be an instrument of Western hegemony.",
            'refs'      => "Brahimi, Lakhdar. 2007. “State Building in Crisis and Post-Conflict Countries.” 7th Global Forum on Reinventing Government. Viena: Organização das Nações Unidas. 1-20.
                            <br/>Kumar, Krishna. 1997. Rebuilding Societies after Civil War: Critical Roles for International Assistance. Boulder: Lynne Rienner.
                            <br/>Labuda, Patryk. 2015. UN Peace Operations: Tracking the Shift from Peacekeeping to Peace Enforcement and State-Building. European Journal of International Law, September 2.
                            <br/>von Bogdandy, Armin, Stefan Häußler, Felix Hanschmann, and Raphael Utz. 2005. State-Building, Nation-Building, and Constitutional Politics in Post-Conflict Situations: Conceptual Clarifications and an Appraisal of Different Approaches. Max Planck Yearbook of United Nations Law, Volume 9, 2005: 579-613."
        ),
        '2' => array (
            'name'      => "Topic B",
            'title'     => "The Situation in Afghanistan",
            'text'      => "The conflict in Afghanistan dates back to 1992, with the collapse of the Soviet-imposed socialist government and the beginning of a civil war between former government figures and a fundamentalist guerrilla, with the subsequent rise of the radical Islamist Taliban regime. In 2001, the attacks against the World Trade Center in New York motivated Bush’s administration to declare a “War on Terror”, with Afghanistan being its first target: the attacks were claimed by the terrorist organization Al Qaeda, based in Afghanistan. The United States and NATO allies thus attacked and dominated the country, defeating the Taliban and establishing a new coalition government. The International Security Assistance Force, as it was named the coalition, remained in Afghan soil for more than 10 years (Visentini 2014).
                            Even ousted from power, the Taliban kept gathering supporters all over the country and acting from Pakistan, which maintained support to Taliban throughout the years. However, NATO began its retreat from Afghanistan in 2012, to be concluded in 2015. With the withdrawal of NATO’s ISAF, Taliban increased its attacks against government forces in several fronts and conquered new territories in the country. The Afghan National Security Forces kept fighting tirelessly, but with lack of resources to engage in more years of combatting. Heavy conflict was held in 2015 over the control of the northern province of Kunduz and the southern Helmand province, geographically and economically important (Almukhtar and Yourish 2015, Azami 2016; Guéhenno 2016; Osman 2015).
                            Not only Taliban emboldened in 2015, but also Al Qaeda skept its traditional strongholds in the country. Besides, the year brought a new element to the fighting: militants pledging alliance to the self-styled Islamic State of Iraq and Syria (ISIS), which has been recruiting youth from Taliban ranks. Even though ISIS is still not a severe threat to Taliban, its presence makes Taliban forces eager to conquer even more provinces – it is estimated that the Taliban officially controls over a fifth of the Afghan territory, but virtually half of it (Simpson 2015; Romero 2015; Almukhtar and Yourish 2015). The escalation of the fighting killed more Afghans in 2015 than in any other year since the US invasion in 2001, and the country is currently second only to Syria when it comes to sources of refugees (Azami 2015; Guéhenno 2016). This situation leads experts to believe the conflict in Afghanistan is nowhere near conclusion, and the US government already decided to maintain its troops in Afghanistan at least until 2017 (Rosenberg and Shear 2015).
                            Bearing all these events in mind, it is time the United Nations Security Council discuss the situation in Afghanistan, which witnesses a worsening humanitarian situation and an increased presence of terrorist organizations such as Al Qaeda and ISIS. With Afghan forces’ resources and control over the country diminishing every day, should the UNSC guarantee further aid and support? For how long will foreign troops still be necessary to tackle these wars? It is clear that the war in Afghanistan involves several actors in the local, regional and international level, and there is a chance that only a coordinated and multinational approach might end one of the world’s most prolonged conflicts.",
            'refs'      => "Almukhtar, Sarah; Yourish, Karen. 2015. “14 Years after U.S. invasion, the Taliban are back in control of large parts of Afghanistan”.  The New York Times.  October 16. http://www.nytimes.com/interactive/2015/09/29/world/asia/afghanistan-taliban-maps.html?_r=1.
                            <br/>Azami, Dawood. 2015. “Analysis: The Taliban’s resurgence in Afghanistan”. Aljazeera. December 27. http://www.aljazeera.com/news/2015/12/analysis-taliban-resurgence-afghanistan-isil-151227065817409.html.
                            <br/>Guéhenno, Jean-Marie. 2016. “10 Conflicts to Watch in 2016”. Foreign Policy. January 3. http://foreignpolicy.com/2016/01/03/10-conflicts-to-watch-in-2016/?utm_content=buffer8b882&utm_medium=social&utm_source=facebook.com&utm_campaign=buffer.
                            <br/>Osman, Borhan. 2015. “Why capturing Helmand is top of the Taliban’s strategic goals”. The Guardian. December 26. http://www.theguardian.com/world/2015/dec/26/taliban-helmand-opium.
                            <br/>Romero, Danny. 2015. “Isis, a year of the caliphate: 4 maps that show how far and fast the group has spread”. The Independent. June 28. http://www.independent.co.uk/news/world/middle-east/isis-a-year-of-the-caliphate-4-maps-that-show-how-far-and-fast-the-group-has-spread-10342191.html.
                            <br/>Rosenberg, Matthew; Shear, Michael. D. 2015. “In Reversal, Obama Says U.S. Soldiers Will Stay in Afghanistan to 2017”. The New York Times. October 15. http://www.nytimes.com/2015/10/16/world/asia/obama-troop-withdrawal-afghanistan.html.
                            <br/>Simpson, Emile. 2015. “The Islamic State of Afghanistan”. Foreign Policy. December 22. http://foreignpolicy.com/2015/12/22/america-needs-to-make-a-deal-with-the-devil-in-helmand/.
                            <br/>United Nations Assistance Mission in Afghanistan. 2015. Frequently Asked Questions https://unama.unmissions.org/frequently-asked-questions.
                            <br/>Visentini, Paulo Gilberto Fagundes. 2014. O Grande Oriente Médio - da descolonização à Primavera Arabe. Campus Elsevier."
        )
    );

?>
