<?php
    $history =
        array(
            array (
                'year'=>'2003',
                'edition'=>'I UFRGSMUN',
                'name'=>'Make your difference: Take care of our world!',
                'info'=>'The first edition of UFRGSMUN, in 2003, simulated five bodies of the United Nations, having a clear message to all of its participants: "Make your difference: take care of our world". During the sessions, delegates immersed in the United Nations system, and debated significant issues and challenges concerning the International Society. The United Nations Environment Programme (UNEP) focused on "Sharing Transboundary Freshwater Resources", and the "Implementation of Certified Emission Reductions". The International Court of Justice (ICJ) presented two cases: the "Case Concerning Oil Platforms (Islamic Republic of Iran v. United States of America)", and the "Case Concerning Avena and Other Mexican Nationals (Mexico v. United States of America)". Delegates at the United Nations Commission on Human Rights (UNCHR) addressed "Worldwide Economic Organizations and Human Rights Promotion", and "Universality of Human Rights". The General Assembly Legal Committee debated "The Legalization of Genetically Modified Food: the Solution to World Hunger?", and the "International Convention against the Reproductive Cloning of Human Beings". And, finally, the United Nations Security Council (UNSC) dealt with two important international issues: "Terrorism and Guerrilla Warfare: How to Deal with These Threats", and "The Situation in Sierra Leone".',
                'website'=>''
            ),
            array (
                'year'=>'2004',
                'edition'=>'II UFRGSMUN',
                'name'=>'A new model to gather different ideas',
                'info'=>'In 2004 UFRGSMUN innovated and presented six simulations of the United Nations organs. Each of the simulations offered participants a great opportunity to exchange experiences and views about topics from different areas, such as peacekeeping operations and indigenous rights, constituting "A new model to gather different ideas". The UNSC invited its delegates to join the debate about "Nation-Building — Strategies and Guidelines for New Conflicts", and "The Kurdish Conflict in Middle East". Judges at ICJ presented the "Advisory opinion requested by the General Assembly — The lawfulness of preventive measures of self-defense", and "The Case Concerning the Gabcíkovo-Nagymaros Project (Slovakia v. Hungary)". The International Law Commission (ILC) discussed "Minimum Standards for Imposing Economic Sanctions", and the "Security Council Reform". At the UNCHR, delegates dealt with two challenging topics: "Human Rights and Biotechnology — The Impacts and Risks of Medical Research Involving Human Beings", and "Human Rights of the Indigenous Peoples at the culmination of the International Decade for Indigenous Peoples: evaluation and prospective plans of action". The Special Political and Decolonization Committee (SPECPOL) addressed both "Self-Determination, Sovereignty and Geopolitical Interests in Strategic Points: The Issue of Gibraltar", and "United Nations Peacekeeping Operations and Transitional Administrations: Extension of the Mandates, Legitimacy and Criteria to Intervention". Lastly, the Assembly of States Parties to the International Criminal Court (ASP) focused on "Bilateral Immunity Agreements: a Challenge to Third Party Jurisdiction", and "The relation between the ICC and the United Nations Security Council".',
                'website'=>''
            ),
            array (
                'year'=>'2005',
                'edition'=>'III UFRGSMUN',
                'name'=>'Because global consciousness turns the world around',
                'info'=>'In 2005, UFRGSMUN delegates were invited to deal with important issues concerning International Society, "because global consciousness turns the world around". The Social, Humanitarian and Cultural Committee (SOCHUM) presented two topics: "Child Trafficking and Intercountry Adoption — a Challenging Relation", and "Participation of Women in Politics and Decision-Making — How Far Have We Come in Equal Opportunities for Women?". SPECPOL dedicated itself to the discussion of "Ensuring Security and Sustainability in Post-elections Iraq — The Role of the United Nations", and the "Trade of Nuclear Materials and Its Impacts to International Security". The Security Council debated "Arms Race in the Threshold of the 21st Century" and "The Crisis in the Sudan and the Prevention of Humanitarian Tragedies". Participants of UFRGSMUN 2005 had possibilities to engage in two different commissions of the Economic and Social Council (ECOSOC). The Commission on Science and Technology for Development debated the issue of "Improving the Policy Environment for the Application of Science and Technology — Intellectual Property Rights in Developing Countries", and "Information and Communication Technologies — Narrowing the Digital Gap". The Commission on Sustainable Development dealt with four different topics: "Energy for Sustainable Development", "Industrial Development", "Air Pollution / Atmosphere", and "Climate Change". The International Law Commission presented two topics: "Current Sources of International Law: towards a Revision of Article 38 of the ICJ Statute", and "Questions Concerning Warfare and Peace Treaties". At last, the United Nations Conference on Trade and Development (UNCTAD) worked with the issue of "Foreign Direct Investments and Local Economies: Attaining a Mutually Beneficial Approach", and "Market Access Measures and Market Entry Conditions as Obstacles to Development".',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2005/'
            ),
            array (
                'year'=>'2006',
                'edition'=>'IV UFRGSMUN',
                'name'=>'Seeking formulas for change',
                'info'=>'In UFRGSMUN 2006 delegates were committed in "Seeking Formulas for Change", and engaged in the challenge of international negotiation and diplomacy in its six committees. At SOCHUM delegates discussed the "Prevention and Treatment of Pandemics – The Access to Medication in the Context of HIV/AIDS and Tuberculosis", and "the Freedom of Expression and Access to Information". The topics proposed at SPECPOL were "Intelligence Agencies and International Peace and Security — Questions Related to Espionage", and "New Paradigms in International Security: Overseas Military Bases Realignment and Closure". The United Nations Security Council dealt with "the Situation in Côte d’Ivoire" and "the Situation in Lebanon". Judges at the International Court of Justice debated the "Case Concerning Certain Criminal Proceedings in France (Congo v. France)", and the "Advisory Opinion on Dismemberment of States and Continuation of Membership in the United Nations". At UNCTAD the "Impacts of Economic Regionalism on Development", and "Labor and Employment in Open Economies" were the topics on the agenda. Finally, in 2006 delegates also had the chance to engage in the discussion of "The India-Pakistan Question: the Situation in the Jammu and Kashmir State" at the Historical United Nations Security Council (HUNSC) of 1948.',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2006/'
            ),
            array (
                'year'=>'2007',
                'edition'=>'V UFRGSMUN',
                'name'=>'Acting for life, dignity and education',
                'info'=>'In UFRGSMUN 2007 delegates were invited to "act for life" and debate issues of fundamental importance to the International Society. Those at the World Bank (WB) discussed Policies for Conflict Prevention. Representatives at the Commission on Crime Prevention and Criminal Justice (CCPCJ) dedicated to analyzing the adoption of "Measures to Combat Trafficking in Firearms" and to address "Financial Havens and their Role in Sheltering Economic Resources to the Transnational Organized Crime". Delegates at the United Nations High Commissioner for Refugees (UNHCR) discussed "The Situation of Refugees, Returnees and Displaced Persons in the Horn of Africa" and the question of "Cooperating with UN Missions to Face Large Scale Environmental Catastrophes: the Case of 2004 Tsunami Emergency in the Indian Ocean". Judges at the International Court of Justice (ICJ) dedicated to the cases of "Ahmadou Sadio Diallo (Republic of Guinea v. Democratic Republic of the Congo)" and "Pulp Mills on the River Uruguay (Argentine Republic vs. Eastern Republic of Uruguay)". At the Special, Political and Decolonization Committee, the topics discussed were "International Nuclear Safeguards for Atomic Energy Production" and "The Risk of Nuclear Proliferation in the Middle East". Finally, delegates at the United Nations Security Council addressed "The Situation in Somalia" and "The Situation Concerning Iraq".',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2007/'
            ),
            array (
                'year'=>'2008',
                'edition'=>'VI UFRGSMUN',
                'name'=>'Reaching a common language',
                'info'=>'In order to "reach a common language" on security, sovereignty, human rights and environmental questions, UFRGSMUN 2008 was composed of six committees. Proposed topics at the SPECPOL were "Cyberterrorism and the Law of Cyber-Space" and "The Use of Private Military Companies and the Privatization of War". Presented cases at the International Court of Justice were an Advisory Opinion on "The Question of Sovereignty in Gibraltar" and the "Dispute concerning navigational and related rights (Costa Rica v. Nicaragua)". The World Bank dealt with "Trade Policies Addressing Climate Change". The UNSC discussed "Threats to International Peace and Security Caused by Terrorist Acts" and "The situation in Afghanistan"; its historical version debated "The situation between Iran and Iraq" in 1986. The Social, Humanitarian and Cultural Committee addressed the issues of "Avoiding Human Rights Abuses in the Name of Counterterrorism Measures" and "Detainees in the context of terrorism: violations of the legal framework".',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2008/'
            ),
            array (
                'year'=>'2009',
                'edition'=>'VII UFRGSMUN',
                'name'=>'Understand. Respect. Change.',
                'info'=>'Understand. Respect. Change." According to those principles, UFRGSMUN 2009 sought to expose contemporary crises and human rights and security-related international grievances. The WB dedicated to the discussion of "Economic and Social Policies Addressing the Global Food Crisis". An Advisory Opinion on the "Accordance with International Law of the Unilateral Declaration of Independence of Kosovo" was pursued at the ICJ. The North Atlantic Treaty Organization (NATO) dealt with "The Russian Crisis". At the Commission on Crime Prevention and Criminal Justice (CCPCJ) "Transnational Organized Crime and Human Trafficking" and "Synthetic Drugs and Crime Prevention" were addressed. And at the United Nations Security Council "The Israeli-Palestinian Conflict" and "Non-proliferation" in Iran were the topics on the agenda.',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2009/'
            ),
            array (
                'year'=>'2010',
                'edition'=>'VIII UFRGSMUN',
                'name'=>'Transcend boundaries. Embrace challenges, innovation and differences.',
                'info'=>'UFRGSMUN 2010 "embraced challenges, differences and innovation in order to transcend boundaries". "The Situation in Sudan" and "The Situation in the Democratic Republic of the Congo" were debated at the United Nations Security Council. "The Question of Central Asia" was the topic under discussion at the North Atlantic Council (NAC). The World Bank focused on "Migrants and Remittances impact on world economy". The ICJ analyzed the "Application of the International Convention on the Elimination of All Forms of Racial Discrimination (Georgia v. Russian Federation)" and "Jurisdictional Immunities of the State (Germany v. Italy)". The United Nations High Commissioner for Refugees (UNHCR) addressed "Climate change and Human Displacement" and the question of "Internally Displaced People". The United Nations Development Programme (UNDP) was dedicated to the "International Management and Environment Impacts of Harmful Substances and Hazardous Waste (HSHW)".',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2010/'
            ),
            array (
                'year'=>'2011',
                'edition'=>'IX UFRGSMUN',
                'name'=>'Understanding beyond solutions. UFRGSMUN: beyond modelling.',
                'info'=>'UFRGSMUN 2011 advocated the idea of "Understanding Beyond Solutions" reinforcing the fact that UFRGSMUN is much more than a Model UN: "UFRGSMUN: Beyond Modelling". Last year delegates at SPECPOL discussed "Multinational sources of fresh water and international security" and "Political, securitarian and infrastructural state-building". The United Nations Human Rights Council (UNHRC) country representatives debated "The activities of Private Military and Security Companies and Human Rights violations" and "Extra-judicial killings: Targeted killing of non-state actors". International Court of Justice judges dedicated themselves to the "Obligation to prosecute or extradite (Belgium v. Senegal)" and the "Application of the Interim Accord of 13 September 1995 (The Former Yugoslav Republic of Macedonia v. Greece)". Delegates at the United Nations Security Council addressed both "The situation in Côte D’Ivoire" and "The situation in Libya". The Board of Executive Directors of the World Bank discussed "Energy Supply in Asia". And, finally, the Association of Southeast Asian Nations Regional Forum (ARF) dealt with "Stability in Northeast Asia: The case of the Korean peninsula" and with "The situation in Myanmar".',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2011/'
            ),
            array (
                'year'=>'2012',
                'edition'=>'X UFRGSMUN',
                'name'=>'Exploring new possibilities, treasuring the past.',
                'info'=>'UFRGSMUN celebrated its 10th edition at 2012, presenting as its main ideal the fact that all that was previously achieved should be treasured and that new possibilities were soon to be open. Delegates discussed at the United Nations Environment Programme (UNEP) "The role of environmental resources in contemporary African conflicts" and the "Protection of marine and coastal ecosystems: economic and political challenges". At the United Nations Human Rights Council (UNHRC), delegates debated "Transitional Justice" and "Transational corporations and Human Rights". International Court of Justice representatives dedicated themselves to the "Immunity of State officials from foreign criminal jurisdiction" and "Most-favoured-nation clause". Country representatives at the United Nations Security Council tackled the topics of "Non-proliferation: the situation in Iran" and "The situation in Syria". The Board of Executive Directors of the World Bank enrolled discussions about "Extractive Industries in Africa". Country representatives also addressed the topic of "UN Reform", at the United nations World Summit on UN Reform. Finally, the Association of Southeast Asian Nations Regional Forum (ARF) addressed both the "ASEAN Vision 2015 and East Asian Integration" and "Maritime Sovereignty in East Asia".',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2012/'
            ),
            array (
                'year'=>'2013',
                'edition'=>'XI UFRGSMUN',
                'name'=>'New perspectives for a changing world.',
                'info'=>'In its XI edition, UFRGSMUN aimed at shedding light over new subjects and at analyzing regions and processes that have long been neglected through renewed perspective. Delegates discussed at the World Bank "Infrastructure investments in the Middle East & North Africa". At the United Nations Human Rights Council (UNHRC), delegates debated "Xenophobic and Racist Legislations" and "Arms Transfers and Human Rights: The Impact on Regions in Conflict". The International Law Commission representatives debated the formation and evidence of customary international law and also the obligation to extradite or prosecute (aut dedere aut judicare). In 2013, representatives at the United Nations Security Council tackled the topics the situation in Mali, and also the very important Responsibility to Protect. The United Nations Environment Programmme (UNEP) enrolled discussions about Environmental Justice and Biodiversity and Gene Patents. Country representatives also addressed the topic of "The Militarization of the Arctic: Political, Economic and Climate Challenges" at the Disarmament and International Security Committee (DISEC). Finally, the newly simulated Shanghai Cooperation Organization Summit (SCO), discussed the Post-War Afghanistan and infrastructure in Central Asia.',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2013/'
            ),
            array (
                'year'=>'2014',
                'edition'=>'XII UFRGSMUN',
                'name'=>'Question old structures. Forge the future.',
                'info'=>'In 2014, UFRGSMUN questioned the old structures present in the international organizations and encouraged participants to discuss so there could be a new future to be forged. Delegates discussed at the Board of Directors of the Asian Development Bank the "Maritime Connectivity in the Asia-Pacific Region".  International Court of Justice representatives dedicated themselves to the "Application of the Convention on the Prevention and Punishment of the Crime of Genocide (Croatia V. Serbia)" and also the access to the Pacific Ocean (Bolivia V. Chile). Country representatives also addressed the topic of foreign military bases and the issue of Military RPAS in foreign airspace at the Disarmament and International Security Committee (DISEC). The representatives at the United Nations Security Council tackled the topics the situation regarding non-state military actors in the Middle East and the Situation in Iraq. Also, for the first time in UFRGSMUN, there was a press committee and a committee in Portuguese: ZOPACAS (Zona de Paz e Cooperação do Atlântico Sul) discussing the presence of foreign powers in the South Atlantic as well as piracy in the Gulf of Guinea. Delegates were also invited to take part of the World Energy Council to debate whether Shale Gas is a revolution in energy affairs and also "Energy Transition and Challenges for the XXI Century". Finally, the complex themes of "Internet Government Surveillance" and "Legal and Political Measures to Address Cybercrime" were discussed at the Ministerial Round Table of the World Summit on the Information Society (WSIS) Forum.',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2014/'
            ),
            array (
                'year'=>'2015',
                'edition'=>'XIII UFRGSMUN',
                'name'=>'Inspire change. Be greater than yourself.',
                'info'=>'In 2014, UFRGSMUN questioned the old structures present in the international organizations and encouraged participants to discuss so there could be a new future to be forged. Delegates discussed at the Board of Directors of the Asian Development Bank the "Maritime Connectivity in the Asia-Pacific Region".  International Court of Justice representatives dedicated themselves to the "Application of the Convention on the Prevention and Punishment of the Crime of Genocide (Croatia V. Serbia)" and also the access to the Pacific Ocean (Bolivia V. Chile). Country representatives also addressed the topic of foreign military bases and the issue of Military RPAS in foreign airspace at the Disarmament and International Security Committee (DISEC). The representatives at the United Nations Security Council tackled the topics the situation regarding non-state military actors in the Middle East and the Situation in Iraq. Also, for the first time in UFRGSMUN, there was a press committee and a committee in Portuguese: ZOPACAS (Zona de Paz e Cooperação do Atlântico Sul) discussing the presence of foreign powers in the South Atlantic as well as piracy in the Gulf of Guinea. Delegates were also invited to take part of the World Energy Council to debate whether Shale Gas is a revolution in energy affairs and also "Energy Transition and Challenges for the XXI Century". Finally, the complex themes of "Internet Government Surveillance" and "Legal and Political Measures to Address Cybercrime" were discussed at the Ministerial Round Table of the World Summit on the Information Society (WSIS) Forum.',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2014/'
            ),
        );
