<?php
    $history =
        array(
            array (
                'year'=>'2003',
                'edition'=>'I UFRGSMUN',
                'name'=>'Faça sua diferença: Cuide de nosso mundo!',
                'info'=>'A primeira edição do UFRGSMUN, em 2003, simulou cinco órgãos das Nações Unidas, passando uma mensagem clara a todos os seus participantes: "Faça a sua diferença: cuide do nosso mundo". Durante as sessões, os delegados imergiram no sistema das Nações Unidas, e debateram questões significativas e desafios relativos à Sociedade Internacional. O Programa das Nações Unidas para o Ambiente (UNEP) focou em "Compartilhamento Transfronteiriços de Recursos de Água Doce", e a "Implementação de Reduções Emissão Certificada". A Corte Internacional de Justiça (CIJ) apresentou dois casos: o "caso referente Plataformas de Petróleo (República Islâmica do Irã v Estados Unidos da América)", e o "processo relativo a Avena e Outros Nacionais Mexicanos (México v Estados Unidos da América)". Os delegados na Comissão das Nações Unidas para os Direitos Humanos (UNCHR) abordaram "Organizações Econômicas Mundiais e Promoção dos Direitos Humanos", e "Universalidade dos Direitos Humanos". O Comitê Jurídico da Assembleia Geral debateu "A legalização de alimentos geneticamente modificados: a solução para a fome no mundo?", e a "Convenção Internacional contra a clonagem reprodutiva dos seres humanos". E, finalmente, o Conselho de Segurança das Nações Unidas (CSNU) tratou de duas questões internacionais importantes: "O terrorismo e a guerrilha: Como lidar com essas ameaças", e “A situação na Serra Leoa".',
                'website'=>''
            ),
            array (
                'year'=>'2004',
                'edition'=>'II UFRGSMUN',
                'name'=>'Um novo modelo para reunir ideias diferentes.',
                'info'=>'Em 2004 UFRGSMUN inovou e apresentou seis simulações dos órgãos das Nações Unidas. Cada uma das simulações ofereceu aos participantes uma grande oportunidade para trocar experiências e pontos de vista sobre temas de diferentes áreas, tais como operações de manutenção da paz e direitos indígenas, constituindo "Um novo modelo para reunir ideias diferentes". O Conselho de Segurança convidou seus delegados para participar do debate sobre a "Nation-Building - estratégias e diretrizes para novos conflitos", e "O conflito curdo no Oriente Médio". Os juízes do TIJ apresentaram a "Opinião consultiva solicitada pela Assembleia Geral - A legalidade das medidas preventivas de autodefesa", e "O processo referente ao Projeto Gabcíkovo-Nagymaros (Eslováquia v Hungria.)". A Comissão de Direito Internacional discutiu "Requisitos Mínimos para a imposição de sanções econômicas", e a "Reforma do Conselho de Segurança". No Conselho de Direitos Humanos das Nações Unidas, os delegados trataram de dois temas desafiadores: "Direitos Humanos e Biotecnologia - Os Impactos e Riscos de Pesquisa Médica Envolvendo Seres Humanos", e "Direitos Humanos dos Povos Indígenas, no auge da Década Internacional dos Povos Indígenas: avaliação e potenciais planos de ação". O Comitê de Descolonização e Políticas Especiais (SPECPOL) voltou-se tanto a "Autodeterminação, soberania e os interesses geopolíticos em pontos estratégicos: a questão de Gibraltar" quanto a "Operações de Manutenção da Paz das Nações Unidas e as Administrações transitórias: Prorrogação dos mandatos, Legitimidade e Critérios de Intervenção”. Por último, a Assembleia dos Estados Partes do Tribunal Penal Internacional (ASP) focou em "Acordos bilaterais de imunidade: um desafio para Terceira Jurisdição", e “A relação entre o ICC e o Conselho de Segurança das Nações Unidas".',
                'website'=>''
            ),
            array (
                'year'=>'2005',
                'edition'=>'III UFRGSMUN',
                'name'=>'Porque consciência global transforma o mundo ao seu redor.',
                'info'=>'Em 2005, os delegados do UFRGSMUN foram convidados a lidar com questões importantes relativas ao Sistema Internacional "porque consciência global transforma o mundo ao seu redor". O Comitê Social Cultural de Ajuda Humanitária (SOCHUM) apresentou dois temas: "Tráfico de Crianças e Adoção Internacional - uma relação desafiadora" e "Participação das Mulheres na Política e Tomada de Decisão - Quão longe chegamos em Igualdade de Oportunidades para as Mulheres?". A SPECPOL se dedicou à discussão de "Garantir a Segurança e Sustentabilidade na pós-eleições no Iraque - O Papel das Nações Unidas", e do "Comércio de Materiais Nucleares e seus impactos para a segurança internacional". O Conselho de Segurança debateu a "Corrida armamentista no Limiar do Século 21" e “A crise no Sudão e a prevenção das tragédias humanitárias". Participantes do UFRGSMUN 2005 tiveram possibilidades de se envolver em duas comissões diferentes do Conselho Econômico e Social (ECOSOC). A Comissão de Ciência e Tecnologia para o Desenvolvimento debateu a questão de "Melhorar a política de ambiente para a Aplicação da Ciência e Tecnologia - Direitos de Propriedade Intelectual em Países em Desenvolvimento", e de "Tecnologias de Informação e Comunicação - reduzir o hiato digital". Na Comissão de Desenvolvimento Sustentável foram tratados quatro temas diferentes: "Energia para o Desenvolvimento Sustentável", "Desenvolvimento Industrial", "Poluição do Ar / Atmosfera", e "Mudanças Climáticas". A Comissão de Direito Internacional apresentou dois temas: "As fontes atuais do Direito Internacional: Revisão do artigo 38 do Estatuto da CIJ", e "Questões concernentes a Guerra e Tratados de Paz". Por fim, a Conferência das Nações Unidas sobre Comércio e Desenvolvimento (UNCTAD) trabalhou com a questão do “Investimento Direto Estrangeiro e as Economias locais: Atingir uma abordagem de vantagens mútuas" e "Medidas de acesso ao mercado e Condições de Entrada no mercado como obstáculos ao desenvolvimento".',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2005/'
            ),
            array (
                'year'=>'2006',
                'edition'=>'IV UFRGSMUN',
                'name'=>'Procurando Fórmulas para a Mudança.',
                'info'=>'No UFRGSMUN 2006, os delegados estavam comprometidos em "procurar fórmulas para a mudança", e engajados no desafio de negociação e diplomacia internacional em seus seis comitês. No SOCHUM, delegados discutiram a "Prevenção e Tratamento das Pandemias - O acesso a medicamentos no contexto do HIV / SIDA e a Tuberculose", e "A Liberdade de Expressão e Acesso à Informação". Os temas propostos pelo SPECPOL eram "Agências de Inteligência e paz e segurança internacionais - Questões relacionadas à espionagem" e "Novos Paradigmas em Segurança Internacional: Realinhamento e fechamento de bases militares além-mar”. O Conselho de Segurança das Nações Unidas tratou de "A situação na Costa do Marfim" e "A situação no Líbano". Juízes do Tribunal Internacional de Justiça debateram o "Caso relativo a determinados procedimentos penais na França (Congo v. França)", e o "Parecer Consultivo sobre desmembramento de Estados e continuação de status de Estado-membro das Nações Unidas". No UNCTAD os "Impactos do Regionalismo Econômico para o Desenvolvimento", e "Trabalho e Emprego em economias abertas" foram os temas da agenda. Finalmente, em 2006, os delegados também tiveram a oportunidade de se envolver na discussão de “A Questão Índia-Paquistão: a situação no Estado de Jammu e Caxemira" no Conselho de Segurança das Nações Unidas Histórico (HUNSC), de 1948.',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2006/'
            ),
            array (
                'year'=>'2007',
                'edition'=>'V UFRGSMUN',
                'name'=>'Agir para a vida, a dignidade e a educação.',
                'info'=>'Em UFRGSMUN 2007 delegados foram convidados a "agir para a vida" e a debater questões de importância fundamental para o Sistema Internacional. Aqueles no Banco Mundial (BM) discutiram Políticas para a Prevenção de Conflitos. Representantes na Comissão de Prevenção de Crimes e Justiça Criminal (CPCJP) dedicaram-se a analisar a adoção de "Medidas para combater o tráfico de armas de fogo" e para tratar "Paraísos fiscais e seu papel na omissão de recursos econômicos para fins de Crime Organizado Transnacional". Os delegados no Alto Comissariado das Nações Unidas para os Refugiados (ACNUR) discutiram "A Situação dos refugiados, repatriados e deslocados no Chifre da África" ​​e a questão da "Cooperar com as missões da ONU para enfrentar catástrofes ambientais de Grande Escala: o caso de Emergência de Tsunami no Oceano Índico em 2004". Juízes do Tribunal Internacional de Justiça (CIJ) dedicaram-se aos casos de "Ahmadou Sadio Diallo (República da Guiné v. República Democrática do Congo)" e “Fábrica de Celulose cerca ao rio Uruguai (República Argentina vs República Oriental do Uruguai)". Na Comissão Especial de Política e Descolonização, os temas abordados foram "Salvaguardas nucleares internacionais para Produção de Energia Atômica" e "O risco de proliferação nuclear no Oriente Médio". Finalmente, os delegados no Conselho de Segurança das Nações Unidas dirigiram "A situação na Somália" e “A situação relativa Iraque".',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2007/'
            ),
            array (
                'year'=>'2008',
                'edition'=>'VI UFRGSMUN',
                'name'=>'Alcançar uma linguagem comum.',
                'info'=>'A fim de "alcançar uma linguagem comum" sobre segurança, soberania, direitos humanos e questões ambientais, o UFRGSMUN de 2008 foi composto por seis comitês. Temas propostos no SPECPOL foram "Ciberterrorismo e a Lei do Ciberespaço" e "O Uso de Empresas Militares Privadas e a Privatização da guerra". Casos apresentados no Tribunal Internacional de Justiça foram de parecer consultivo sobre "A questão da soberania em Gibraltar" e "Litígio relativo direitos de navegação e afins (Costa Rica v. Nicarágua)". O Banco Mundial tratou de "Políticas Comerciais voltadas para a mudança climática". O CSNU discutiu "As ameaças à paz e segurança internacionais causada por atos terroristas" e "A situação no Afeganistão"; sua versão histórica debateu "A situação entre o Irã e o Iraque", em 1986. O Comitê Social, Humanitário e Cultural abordou as questões de "Evitar abusos de direitos humanos em nome de medidas contra o terrorismo" e "Os detidos no contexto do terrorismo: violações de quadro jurídico".',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2008/'
            ),
            array (
                'year'=>'2009',
                'edition'=>'VII UFRGSMUN',
                'name'=>'Entenda. Respeite. Mude.',
                'info'=>'"Entenda. Respeite. Mude”. De acordo com esses princípios, UFRGSMUN 2009 procurou expor crises contemporâneas relacionadas a ameaças à segurança internacional e desrespeito dos direitos humanos. O WB dedicou-se à discussão de "políticas econômicas e sociais de enfrentamento da crise global de alimentos". Um parecer consultivo sobre a "conformidade com o direito internacional da declaração unilateral de independência do Kosovo" foi perseguido na CIJ. A Organização do Tratado do Atlântico Norte (OTAN) lidou com "a crise da Rússia". Na Comissão sobre Prevenção ao Crime e Justiça Criminal (CPCJP) "Crime Organizado Transnacional e Tráfico de Seres Humanos" e "drogas sintéticas e Prevenção do Crime" foram abordados. E no Conselho de Segurança das Nações Unidas "O conflito Israel-Palestina" e "não proliferação no Irã” foram os temas da agenda.',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2009/'
            ),
            array (
                'year'=>'2010',
                'edition'=>'VIII UFRGSMUN',
                'name'=>'Transcender fronteiras. Abraçar desafios, inovação e diferenças.',
                'info'=>'UFRGSMUN 2010 se propôs a "abraçar desafios, diferenças e inovação, a fim de transcender as fronteiras". "A situação no Sudão" e "a situação na República Democrática do Congo" foram debatidas no Conselho de Segurança das Nações Unidas. "A questão da Ásia Central" foi o tema em discussão no Conselho do Atlântico Norte (NAC). O Banco Mundial focou em "o impacto de migrantes e remessas na economia mundial". A CIJ analisou a "Aplicação da Convenção Internacional sobre a Eliminação de Todas as Formas de Discriminação Racial (Georgia v. Rússia)" e "Imunidades Jurisdicionais do Estado (Alemanha v. Italy)". O Alto Comissariado das Nações Unidas para os Refugiados (ACNUR) abordou "A mudança climática e deslocamentos humanos" e a questão das "Pessoas Internamente Deslocadas". O Programa de Desenvolvimento das Nações Unidas (PNUD) se dedicou a debater "gestão Internacional e Meio Ambiente Impactos de substâncias nocivas e resíduos perigosos".',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2010/'
            ),
            array (
                'year'=>'2011',
                'edition'=>'IX UFRGSMUN',
                'name'=>'Entendimento além das soluções. UFRGSMUN: além da simulação.',
                'info'=>'UFRGSMUN 2011 defendia a ideia de "compreender além das soluções" reforçando o fato de que UFRGSMUN se propõe a ser muito mais do que um modelo da ONU. Delegados do último ano na SPECPOL discutiram "fontes multinacionais de água doce e segurança internacional" e "construção política, securitária e infraestrutural do Estado". Os representantes dos países do Conselho de Direitos Humanos das Nações Unidas debateram "As atividades de empresas privadas militares e de segurança e violações dos direitos humanos" e "assassinatos extra-judiciais: assassinato seletivo de atores não-estatais". Na Corte Internacional de Justiça, juízes dedicaram-se à "obrigação de processar ou extraditar (Bélgica v. Senegal)" e "Aplicação do Acordo Provisório de 13 de Setembro de 1995 (Antiga República Jugoslava da Macedônia v. Grécia)". Delegados no Conselho de Segurança das Nações Unidas debateram tanto "A situação na Costa do Marfim" como "A situação na Líbia". O Conselho de Diretores Executivos do Banco Mundial discutiu "Suprimento de Energia na Ásia". E, finalmente, a Associação do Sudeste Asiático Fórum Regional Unidas lidou com "A estabilidade no nordeste da Ásia: O caso da península coreana" e com "A situação em Myanmar".',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2011/'
            ),
            array (
                'year'=>'2012',
                'edition'=>'X UFRGSMUN',
                'name'=>'Explorando novas possibilidades, valorizando o passado.',
                'info'=>'UFRGSMUN comemorou sua 10ª edição em 2012, apresentando como principal ideal o fato de que tudo o que foi anteriormente alcançado deve ser estimado e que novas possibilidades logo seriam abertas.. Delegados discutiram, no Programa das Nações Unidas para o Ambiente (PNUMA), "O papel dos recursos ambientais em conflitos africanos contemporâneos" e "Proteção dos ecossistemas marinhos e costeiros: desafios econômicos e políticos". No Conselho de Direitos Humanos das Nações Unidas, os delegados debateram "Justiça de Transição" e "Corporações Transnacionais e Direitos Humanos". Na Corte Internacional de Justiça, representantes dedicaram-se à "Imunidade dos funcionários do Estado de jurisdição penal estrangeira" e "cláusula da nação mais favorecida". Representantes dos países no Conselho de Segurança das Nações Unidas abordaram os temas da "não proliferação: a situação no Irã" e "A situação na Síria". O Conselho de Administração Executivo do Banco Mundial promoveu discussões sobre "Indústrias extrativas na África". Representantes dos países também abordaram o tema "Reforma da ONU", na Conferência Mundial sobre a Reforma das Nações Unidas Nações Unidas. Finalmente, o Fórum Regional da ASEAN dirige-se tanto a "ASEAN: Visão 2015 e Integração do Leste Asiático" e "Soberania Marítima no Leste da Ásia".',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2012/'
            ),
            array (
                'year'=>'2013',
                'edition'=>'XI UFRGSMUN',
                'name'=>'Novas perspectivas para um mundo em mudança.',
                'info'=>'Na sua XI edição, UFRGSMUN destinou-se a lançar luz sobre novos temas e analisar as regiões e os processos que têm sido negligenciadas por meio perspectiva renovada. Os delegados discutiram no Banco Mundial "Os investimentos em infraestrutura no Oriente Médio e Norte da África". No Conselho de Direitos Humanos das Nações Unidas, os delegados debateram "Legislações xenófobas e racistas" e "Transferências de Armas e Direitos Humanos: o impacto nas regiões em conflito." Os representantes da Comissão de Direito Internacional debateram a formação e as provas do direito costumeiro internacional e também a obrigação de extraditar ou processar (aut dedere aut judicare). Em 2013, o Conselho de Segurança das Nações Unidas abordou os temas da situação no Mali, e também a Responsabilidade de Proteger. O Programa Ambiental das Nações Unidas se propôs a discutir sobre Justiça Ambiental e Biodiversidade e Patentes de Genes. Representantes de países também puderam discutir o tema "A militarização do Ártico: Política, Economia e Desafios Climáticos" no Comitê de Desarmamento e Segurança Internacional. Finalmente, a Organização para Cooperação de Xangai discutiu o pós-guerra no Afeganistão e infraestrutura na Ásia Central.',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2013/'
            ),
            array (
                'year'=>'2014',
                'edition'=>'XII UFRGSMUN',
                'name'=>'Questione antigas estruturas. Forje o futuro.',
                'info'=>'Em 2014, UFRGSMUN questionou as velhas estruturas presentes nas organizações internacionais e encorajou os participantes a discutir para que um novo futuro pudesse ser forjado. Delegados discutiram no Conselho de Diretores do Banco Asiático de Desenvolvimento a "Conectividade Marítima na Região Ásia-Pacífico". Os representantes da Corte Internacional de Justiça dedicaram-se à "Aplicação da Convenção sobre a Prevenção e Repressão do Crime de Genocídio (Croácia V. Sérvia)" e também o acesso ao Oceano Pacífico (Bolívia V. Chile). Representantes dos países também abordaram o tema das bases militares estrangeiras e a emissão de RPAS militares no espaço aéreo estrangeiro no Comitê de Desarmamento e Segurança Internacional. Os representantes no Conselho de Segurança das Nações Unidas abordaram os temas da situação de atores militares não estatais no Médio Oriente e a situação no Iraque. Além disso, pela primeira vez em UFRGSMUN, houve um comitê de imprensa e um comitê em português: ZOPACAS (Zona de Paz e Cooperação do Atlântico Sul) discutiu a presença de forças estrangeiras no Atlântico Sul, bem como a pirataria no Golfo da Guiné. Os delegados também foram convidados a participar do Conselho Mundial de Energia para debater dois tópicos: “Gás de Xisto: revolução?” e “Transição energética e desafios para o século XXI”. Finalmente, os temas complexos de "Vigilância Governamental da Internet" e "Medidas Legais e Políticas para Enfrentar o Cibercrime" foram discutidos na reunião ministerial Mesa Redonda da Cúpula Mundial sobre a Sociedade da Informação (CMSI) Fórum.',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2014/'
            ),
            array (
                'year'=>'2015',
                'edition'=>'XIII UFRGSMUN',
                'name'=>'Inspire mudança. Seja maior que você mesmo.',
                'info'=>'A edição XIII propôs a inspirar os participantes a agir a fim de não só ajudar o mundo a mudar, mas também para inspirar os outros a segui-lo nesse desafio. Os delegados discutiram na Cooperação Econômica Ásia-Pacífico o tópico de "Acordos de Livre Comércio na região Ásia-Pacífico”. Pela primeira vez, UFRGSMUN simulou um gabinete de crises: a "Força-Tarefa Conjunta Combinada - Operação Resolução Inerente". Dois comitês foram simulados em Português: Conselho Sul-Americano de Infraestrutura e Planejamento (COSIPLAN) discutiu "Reformulação dos Eixos da IIRSA" e "O Eixo Hidroviário Sul-americano"; e do Conselho de Paz e Segurança da União Africano "Grupos Militares Não-Estatais no Sahara-Sahel" e "A Situação na Líbia". O Comitê de Desarmamento e Segurança Internacional discutiu "Sistema de Defesa Antimísseis" e "Prevenção contra Corrida Armamentista no Espaço Sideral". O comitê jurídico foi o Comitê Internacional da Lei que abordou o tema de "Crimes contra a Humanidade". O Comité Internacional de Imprensa cresceu para cobrir os eventos e todos os comitês. O Conselho de Direitos Humanos das Nações Unidas trouxe os temas de "Discutindo Conflito sobre uma Perspectiva de Gênero: Mulheres e a reforma do Setor da Segurança Internacional" e "Desenvolvimento Urbano: Consequências para o Direito à Moradia Adequada". Finalmente, os delegados do Conselho de Segurança das Nações Unidas foram convidados a falar sobre "A Situação na Ucrânia" e "A Situação no Iêmen".',
                'website'=>'http://www.ufrgs.br/ufrgsmun/2014/'
            ),
        );
